import {chromium} from 'playwright';import {readFileSync,writeFileSync} from 'node:fs';import assert from 'node:assert/strict';
const dir='C:/JensenBot/Tooling/PundiWebAstraLaunch/evidence/r2',url='http://127.0.0.1:4322/';
const b=await chromium.launch({headless:true,channel:'chrome'}),c=await b.newContext({locale:'id-ID',serviceWorkers:'block'});await c.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());const p=await c.newPage();const out={views:[],fx:{},routes:[]};const errors=[];p.on('pageerror',e=>errors.push(e.message));
for(const region of ['ID','US'])for(const [width,height]of [[390,844],[768,1024],[1280,720],[1366,768],[1440,900],[1920,1080]]){await p.setViewportSize({width,height});await p.goto(url);await p.locator(`[data-region=${region}]`).click();await p.evaluate(async()=>{await document.fonts.ready;for(const i of document.images){i.loading='eager';if(getComputedStyle(i).display!=='none')await i.decode().catch(()=>{});}});await p.addScriptTag({path:'node_modules/axe-core/axe.min.js'});const violations=await p.evaluate(async()=> (await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}})).violations.map(x=>({id:x.id,nodes:x.nodes.map(n=>n.target)})));const layout=await p.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,clipped:[...document.querySelectorAll('h1,h2,p,a,button')].filter(e=>{const r=e.getBoundingClientRect();return r.width&&getComputedStyle(e).position!=='absolute'&&(r.right>innerWidth+1||r.left< -1)}).map(e=>e.textContent.slice(0,30)),broken:[...document.images].filter(i=>!i.naturalWidth).map(i=>i.src),language:document.documentElement.lang,price:document.querySelector('#price').textContent,words:document.body.innerText.split(/\s+/).length}));await p.screenshot({path:`${dir}/${region}-${width}.png`,fullPage:true});out.views.push({region,width,height,violations,...layout});}
await p.locator('[data-region=ID]').click();await p.reload();assert.equal(await p.locator('html').getAttribute('lang'),'id');await p.locator('[data-region=US]').click();await p.reload();assert.equal(await p.locator('html').getAttribute('lang'),'en');out.persistence=true;await p.waitForTimeout(300);out.fx.realUnavailable=await p.locator('#price').textContent()==='Rp49.000';
await p.route('**/api/stocks/fx',r=>r.fulfill({json:{pair:'USD/IDR',rate:16000,asOf:new Date().toISOString()}}));await p.reload();await p.waitForFunction(()=>document.querySelector('#price').textContent.includes('$'));out.fx.mockConversion=await p.locator('#price').textContent();assert.equal(out.fx.mockConversion,'≈ $3.06');
await p.route('**/api/stocks/fx',r=>r.fulfill({status:503,json:{error:'test failure'}}));await p.reload();assert.equal(await p.locator('#price').textContent(),'≈ $3.06');out.fx.safeCache=true;
await p.evaluate(()=>localStorage.setItem('pundi-public-fx-v1',JSON.stringify({pair:'USD/IDR',rate:16000,asOf:Date.now()-8*864e5})));await p.reload();assert.equal(await p.locator('#price').textContent(),'Rp49.000');out.fx.expiredRejected=true;
await p.evaluate(()=>localStorage.removeItem('pundi-public-fx-v1'));await p.route('**/api/stocks/fx',r=>r.fulfill({json:{pair:'USD/IDR',rate:-10,asOf:new Date().toISOString()}}));await p.reload();await p.waitForTimeout(200);assert.equal(await p.locator('#price').textContent(),'Rp49.000');out.fx.invalidRejected=true;
await p.locator('[data-region=ID]').click();assert.equal(await p.locator('#price').textContent(),'Rp49.000');out.fx.switchBack=true;
for(const route of ['/','/app.html','/auth/reset-password','/privacy','/terms','/support','/robots.txt','/sitemap.xml']){const r=await p.goto(new URL(route,url).href);out.routes.push({route,status:r.status()});if(route==='/app.html'){await p.locator('#authGate').waitFor({state:'visible'});await p.locator('#authModeToggle').click();assert.ok(await p.locator('#authConfirm').isVisible());await p.locator('#authModeToggle').click();await p.locator('#authForgotPassword').click();assert.equal(await p.locator('#authTitle').textContent(),'Reset password');out.authSmoke=true;}}
await p.goto(url);out.seo=await p.evaluate(()=>({canonical:document.querySelector('[rel=canonical]').href,h1:document.querySelectorAll('h1').length,schema:JSON.parse(document.querySelector('[type="application/ld+json"]').textContent),og:document.querySelector('[property="og:image"]').content}));
await p.keyboard.press('Tab');out.keyboard=await p.locator('.skip-link').evaluate(e=>document.activeElement===e);out.errors=errors;out.pass=out.views.every(v=>!v.overflow&&!v.clipped.length&&!v.broken.length&&!v.violations.length)&&out.routes.every(r=>r.status===200)&&out.authSmoke&&out.keyboard&&!errors.length;writeFileSync(`${dir}/qa.json`,JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));await b.close();if(!out.pass)process.exitCode=1;
