import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const read = path => readFileSync(resolve(root, path), "utf8");
const manifest = JSON.parse(read("public/manifest.webmanifest"));
assert.equal(manifest.name, "CVFinance");
assert.equal(manifest.display, "standalone");
for (const icon of manifest.icons) assert.ok(existsSync(resolve(root, "public", icon.src.replace(/^\//, ""))), `Missing ${icon.src}`);

const index = read("index.html");
const css = read("styles.css");
for (const tab of ["accumulation","cashflow","expenses","clients","stocks","trading","electricity","prospect","insights"]) assert.match(index, new RegExp(`id="${tab}"`));
assert.equal((index.match(/data-page="stocks"/g)||[]).length,2,"Sidebar and data menu must expose one Assets destination");
assert.match(index,/data-page="stocks"[^>]*>[\s\S]*?Assets/,"The existing Stocks destination must be displayed as Assets");
assert.doesNotMatch(index,/<span>Stocks<\/span>|>Stocks<\/button>/,"The top-level navigation label must no longer display Stocks");
assert.doesNotMatch(index,/data-page="trading"/,"Trading must live inside Stocks instead of a separate route");
assert.match(index,/data-stock-workspace="investment"/);assert.match(index,/data-stock-workspace="trading"/);
assert.match(index,/id="dividendTickerList"/);assert.match(index,/id="investmentDepositBtn"/);
for(const marker of ["data-investment-edit=\"IDR\"","data-investment-edit=\"USD\"","data-trading-edit=\"IDR\"","data-trading-edit=\"USD\""])assert.match(index,new RegExp(marker));
assert.match(index, /manifest\.webmanifest/);
assert.match(index, /authForm/);
assert.match(index, /annualPerformanceDashboard/);
assert.match(index, /Decision Metrics/);
assert.match(index, /target-price-board/);
assert.match(index, /insightActionPlan/);
assert.match(index, /id="cashMonthExpense"/, "History must show one current-month expense headline");
assert.doesNotMatch(index, /id="cashIncome"|id="cashExpense"|id="cashNet"/, "The old three History summary cards must be removed");
assert.match(index, /id="cashChannelDonut"/);
assert.match(index, /id="cashChannelLegend"/);
assert.ok(index.indexOf('id="txDescription"') < index.indexOf('id="txAmount"'), "Transaction Description must appear above Amount");
assert.match(index,/data-page="clients"[^>]*>[\s\S]*?<span>Income<\/span>/,"Desktop navigation must expose Income as the parent category");
assert.match(index,/class="segmented workspace-tabs income-workspace-tabs"/,"Income must have a Stocks-style Clients subcategory switcher");
assert.match(index,/class="segmented workspace-tabs history-workspace-tabs"/,"History filters must share the Stocks workspace tab design");
assert.match(index,/id="sideAvailableBalance"/,"Desktop sidebar must show Accumulation Available Balance above projections");
assert.match(index,/id="mobileMenuBtn"[^>]*aria-controls="primarySidebar"/,"Mobile header must expose an accessible hamburger control");
assert.match(index,/id="mobileMenuBackdrop"/,"Mobile drawer must include a dismissible backdrop");
assert.match(index,/class="mobile-add-transaction"[^>]*data-open-tx/,"Mobile must retain one floating transaction action");
assert.doesNotMatch(index,/class="mobile-nav"/,"The crowded mobile bottom navigation must be removed");
assert.match(index,/mobile-drawer\.css/);
const drawerCss=read("mobile-drawer.css");
assert.match(drawerCss,/v8\.1\.1 simple mobile drawer navigation/);
assert.match(drawerCss,/body\.mobile-menu-open \.sidebar/);

const sql = read("supabase/migrations/001_initial_schema.sql");
for (const table of ["profiles","accounts","transactions","monthly_budgets","yearly_expenses","planned_events","credit_facilities","credit_items","clients","stock_holdings","stock_price_targets","electricity_readings","app_settings"]) {
  assert.match(sql, new RegExp(`create table if not exists public\\.${table}`));
}
assert.match(sql, /enable row level security/);
assert.match(sql, /auth\.uid\(\)/);

const env = read(".env.example");
for (const key of ["FINNHUB_API_KEY","TWELVE_DATA_API_KEY","SUPABASE_URL","SUPABASE_ANON_KEY"]) assert.match(env, new RegExp(`^${key}=`, "m"));
const serviceWorker = read("public/sw.js");
assert.match(serviceWorker, /pathname\.startsWith\("\/api\/"\)/);

const jsFiles = ["app.js","api/config.js","api/_lib/rate-limit.js","api/_lib/dividends.js","api/stocks/dividends.js","api/stocks/fx.js","api/stocks/quote.js","api/stocks/validate.js","api/trading/quote.js","api/trading/benchmark.js","api/cron/refresh-stocks.js","api/crypto/quote.js","src/data/default-data.js","src/data/finance-model.js","src/data/electricity-model.js","src/data/currency-format.js","src/crypto/binance.js","src/data/repository.js","src/lib/idb.js","src/lib/supabase.js","src/stocks/client.js","src/stocks/dividends.js","src/stocks/holding.js","src/trading/model.js","src/trading/crypto-lifecycle.js","src/sync/sync-manager.js"];
for (const file of jsFiles) execFileSync(process.execPath, ["--check", resolve(root, file)], { stdio:"pipe" });

for (const file of jsFiles.map(read)) {
  assert.ok(!/sk_live_|service_role\s*[:=]\s*[A-Za-z0-9_-]{20,}/.test(file), "Possible committed secret detected");
}

const { createMvpSeed } = await import("../src/data/default-data.js");
const seed = createMvpSeed();
assert.equal(seed.accounts.reduce((sum, row) => sum + row.balance, 0), 14007953);
assert.equal(seed.clients.reduce((sum, row) => sum + row.monthly, 0), 10500000);
assert.equal(seed.stocks.find(row => row.ticker === "WDC").quantity, 2.8033875);
assert.equal(seed.rateKwh, 1740);
assert.ok(seed.budgets.some(row => row.category === "Food") && seed.budgets.some(row => row.category === "Coffee"));

const { electricityPeriods, latestElectricityBalance, parseTopUpAmount } = await import("../src/data/electricity-model.js");
const readingA = {id:"reading-a",date:"2026-08-19",time:"19:00",remaining:398.07};
const readingB = {id:"reading-b",date:"2026-08-20",time:"19:00",remaining:188.84};
const unchangedAfterFutureTopUp = electricityPeriods([readingA,readingB],[{id:"topup-after",date:"2026-08-20",time:"22:45",amount:100}])[0];
assert.equal(unchangedAfterFutureTopUp.status,"valid");
assert.ok(Math.abs(unchangedAfterFutureTopUp.used-209.23)<1e-9,"A top-up after the latest reading must not rewrite completed usage");
assert.ok(Math.abs(latestElectricityBalance([readingA,readingB],[{id:"topup-100",date:"2026-08-20",time:"22:45",amount:100}])-288.84)<1e-9,"Latest balance must add top-ups after the latest physical reading");
const oneTopUpPeriod = electricityPeriods([{date:"2026-08-20",time:"19:00",remaining:188.84},{date:"2026-08-21",time:"19:00",remaining:250}],[{date:"2026-08-20",time:"22:45",amount:100}])[0];
assert.ok(Math.abs(oneTopUpPeriod.used-38.84)<1e-9,"One top-up must reconcile into the next physical interval");
const twoTopUpPeriod = electricityPeriods([{date:"2026-08-20",time:"19:00",remaining:188.84},{date:"2026-08-21",time:"19:00",remaining:200}],[{date:"2026-08-20",time:"22:45",amount:100},{date:"2026-08-20",time:"23:15",amount:50}])[0];
assert.ok(Math.abs(twoTopUpPeriod.used-138.84)<1e-9,"Multiple top-ups must all reconcile once into the next physical interval");
const noTopUpPeriod = electricityPeriods([readingA,readingB],[])[0];
assert.ok(Math.abs(noTopUpPeriod.used-209.23)<1e-9,"No top-up must preserve the existing physical-reading formula");
const anomalousPeriod = electricityPeriods([{date:"2026-08-20",time:"19:00",remaining:188.84},{date:"2026-08-21",time:"19:00",remaining:300}],[])[0];
assert.equal(anomalousPeriod.status,"anomaly","Negative calculated consumption must be explicit");
assert.ok(anomalousPeriod.rawUsed<0,"Anomalous intervals must retain their negative raw result");
assert.equal(anomalousPeriod.used,null,"Anomalous intervals must not silently become zero usage");
assert.equal(parseTopUpAmount(""),null,"Empty top-up amounts must be rejected");
assert.equal(parseTopUpAmount("not-a-number"),null,"NaN top-up amounts must be rejected");
assert.equal(parseTopUpAmount(-1),null,"Negative top-up amounts must be rejected");
assert.equal(parseTopUpAmount(0),null,"Zero top-up amounts must be rejected");
assert.equal(parseTopUpAmount("12.5"),12.5,"Decimal top-up amounts must be accepted");

const { formatCryptoQuote, formatFiatCurrency } = await import("../src/data/currency-format.js");
assert.doesNotThrow(()=>formatFiatCurrency(72081.90,"USDT"),"USDT must never be passed to Intl as a fiat currency code");
assert.match(formatFiatCurrency(72081.90,"USDT"),/USDT$/,"USDT must display as a numeric quote with an explicit suffix");
assert.match(formatCryptoQuote(0.00005,"USDT"),/USDT$/,"Small crypto quantities/quotes must remain format-safe");
assert.match(formatFiatCurrency(72081.90,"USD"),/\$/,"USD fiat formatting must remain unchanged");
assert.match(formatFiatCurrency(72081.90,"IDR"),/IDR|Rp/,"IDR fiat formatting must remain unchanged");

const { binanceSpotSymbol, convertCryptoPrice, cryptoBaseSymbol, isCryptoAsset, normalizeCryptoSymbol, parseCryptoPairInput } = await import("../src/crypto/binance.js");
assert.equal(normalizeCryptoSymbol("btc"),"BTC","Crypto symbols must normalize to uppercase base symbols");
assert.equal(binanceSpotSymbol("btc"),"BTCUSDT","Crypto symbols must map to the default USDT spot pair");
assert.equal(cryptoBaseSymbol("BTCUSDT"),"BTC","Provider pairs must resolve back to their base symbol");
assert.deepEqual(parseCryptoPairInput("BTC"),{baseSymbol:"BTC",requestedQuote:"USD",explicitQuote:false});
assert.deepEqual(parseCryptoPairInput("BTCUSD"),{baseSymbol:"BTC",requestedQuote:"USD",explicitQuote:true});
assert.deepEqual(parseCryptoPairInput("BTC/IDR"),{baseSymbol:"BTC",requestedQuote:"IDR",explicitQuote:true});
assert.deepEqual(parseCryptoPairInput("BTC-USDT"),{baseSymbol:"BTC",requestedQuote:"USDT",explicitQuote:true});
assert.deepEqual(parseCryptoPairInput("btc_idr"),{baseSymbol:"BTC",requestedQuote:"IDR",explicitQuote:true});
assert.equal(convertCryptoPrice(70000,"USDT","USD",16250),70000);
assert.equal(convertCryptoPrice(70000,"USDT","IDR",16250),1137500000);
assert.equal(convertCryptoPrice(1137500000,"IDR","USD",16250),70000);
assert.equal(isCryptoAsset({assetType:"crypto",market:"CRYPTO",currency:"USDT"}),true);
assert.equal(isCryptoAsset({market:"NASDAQ",currency:"USD"}),false);
assert.throws(()=>normalizeCryptoSymbol("BTC/USDT"),/Invalid crypto symbol/);

const { annualOperatingPerformance, buildMonthlyTimeline, buildProjection, getBudgetProgress, getClientPaidThisMonth, getCurrentNetWorth, getEntrustedDeduction, getFixedIncome, getTotalOutstanding, remainingYearExpenseBreakdown, remainingYearIncomeBreakdown, transactionsForMonth } = await import("../src/data/finance-model.js");
const modelClients = [
  {monthly:1000000,paid:300000,carry:0,status:"pending",clientType:"recurring"},
  {monthly:2000000,paid:0,carry:0,status:"pending",clientType:"ending",endingPaid:false},
  {monthly:3000000,paid:3000000,carry:0,status:"paid",clientType:"ending",endingPaid:true}
];
assert.equal(getFixedIncome(modelClients),1000000,"Ending clients must not enter recurring income");
assert.deepEqual(annualOperatingPerformance({clients:modelClients,budgets:[{monthly:1000000},{monthly:-500000}],yearly:[{amount:2000000},{amount:-1000000}]}),{income:12000000,monthlyExpense:18000000,yearlyExpense:3000000,expense:21000000,net:-9000000},"Annual operating dashboard must use recurring income and absolute monthly/yearly budgets only");
assert.equal(getTotalOutstanding(modelClients),2700000,"Unpaid ending balances remain receivables");
assert.equal(getCurrentNetWorth(10000000,5000000),15000000,"Accumulation is current liquid plus stocks only");
const entrusted=[{amount:1500000,source:"cash",settled:false},{amount:750000,source:"stocks",settled:false},{amount:900000,source:"cash",settled:true}];
assert.equal(getEntrustedDeduction(entrusted),2250000,"Only active entrusted funds reduce net worth");
assert.equal(getEntrustedDeduction(entrusted,"cash"),1500000,"Cash and stock entrusted deductions remain separate");
assert.equal(getCurrentNetWorth(10000000-getEntrustedDeduction(entrusted,"cash"),5000000-getEntrustedDeduction(entrusted,"stocks")),12750000,"Entrusted funds reduce their selected asset source exactly once");
const referenceDate=new Date("2026-08-07T12:00:00+07:00");
const monthlyLedger=[{id:"jul",type:"expense",amount:700000,date:"2026-07-31",category:"Food",channel:"GoFood"},{id:"aug",type:"expense",amount:800000,date:"2026-08-01",category:"Food",channel:"GrabFood"}];
assert.deepEqual(transactionsForMonth(monthlyLedger,2026,7).map(row=>row.id),["aug"],"A new History month must start from only its own dated records");
assert.equal(monthlyLedger.length,2,"Monthly History reset must never delete archived transactions");
const rolledClient={monthly:1000000,paid:1000000,carry:0,status:"paid",clientType:"recurring",trackingMonth:"2026-07"};
assert.equal(getClientPaidThisMonth(rolledClient,referenceDate),0,"Recurring client paid state must reset automatically in a new month");
assert.equal(getTotalOutstanding([rolledClient],referenceDate),1000000,"A new month must restore the recurring invoice without deleting history");
const modelBudgets=[{category:"Food",monthly:1000000,paymentStatus:"partial",paidAmount:400000,trackingMonth:"2026-08"}];
const modelYearly=[{amount:1000000,month:"August",lastPaidYear:null},{amount:2000000,month:"October",lastPaidYear:null},{amount:3000000,month:"June",lastPaidYear:2026}];
const modelEvents=[{date:"2026-08-20",amount:500000},{date:"2028-07-01",amount:5000000}];
const modelCredit=[{due:"2026-08-26",amount:100000,paid:false},{due:"2026-09-26",amount:200000,paid:false},{due:"2027-04-26",amount:300000,paid:false}];
const modelTransactions=[{type:"income",amount:400000,date:"2026-08-05"},{type:"expense",amount:900000,date:"2026-08-05",category:"Food"}];
assert.deepEqual(getBudgetProgress(modelBudgets[0],modelTransactions,referenceDate),{status:"partial",paid:400000,remaining:600000,autoPaid:900000,trackingMonth:"2026-08"},"Manual partial progress must override History without changing the default budget");
assert.deepEqual(remainingYearExpenseBreakdown({referenceDate,budgets:modelBudgets,yearly:modelYearly,events:modelEvents,credit:modelCredit,transactions:modelTransactions}),{recurring:4600000,yearly:3000000,events:500000,eventOnly:500000,credit:300000,total:8400000},"Remaining-year expense must separate one-time events and dated credit");
assert.deepEqual(remainingYearIncomeBreakdown({referenceDate,clients:modelClients,transactions:modelTransactions}),{outstanding:2700000,recurring:4000000,additional:0,total:6700000},"History income must remain ledger-only and never enter projection");
const monthly=buildMonthlyTimeline({referenceDate,accountTotal:10000000,clients:modelClients,budgets:modelBudgets,yearly:modelYearly,events:modelEvents,credit:modelCredit,transactions:modelTransactions,portfolioForYear:()=>0});
assert.deepEqual(monthly.map(row=>row.cash),[10500000,10300000,8300000,8300000,8300000],"Current month uses receivables and planned obligations while ignoring History cashflow");
const modelProjection = buildProjection({
  years:[2026,2027,2028],referenceDate,accountTotal:10000000,clients:modelClients,budgets:modelBudgets,
  yearly:modelYearly,events:modelEvents,credit:modelCredit,transactions:modelTransactions,portfolioForYear:()=>0
});
assert.deepEqual(modelProjection.map(row=>row.closing),[8300000,2000000,-9000000],"Projection must carry closing cash forward, ignore History, and deduct obligations only in their matching year");
assert.equal(modelProjection[0].expenses.currentMonth,600000,"Current-month remaining budget must be disclosed separately");
assert.equal(modelProjection[0].expenses.recurring,4000000,"August projection must show exactly four full recurring expense months after August");
assert.equal(modelProjection[0].incomeBreakdown.recurring,4000000,"August projection must show exactly four full recurring income months after August");
for (const row of modelProjection) assert.equal(row.nw,row.opening+row.portfolio+row.incomeBreakdown.total-row.expenses.total,`Headline ${row.year} must equal its visible equation`);
assert.equal(modelProjection[0].expenses.credit,300000,"Only unpaid credit due in the current year belongs in 2026");
assert.equal(modelProjection[1].expenses.credit,300000,"Credit due in 2027 appears once in 2027");
assert.equal(modelProjection[2].expenses.credit,0,"Credit must not recur after its due year");
const projectionWithoutHistory=buildProjection({years:[2026,2027,2028],referenceDate,accountTotal:10000000,clients:modelClients,budgets:modelBudgets,yearly:modelYearly,events:modelEvents,credit:modelCredit,transactions:[],portfolioForYear:()=>0});
assert.deepEqual(modelProjection.map(row=>row.nw),projectionWithoutHistory.map(row=>row.nw),"Income and expense History entries must never change Net Worth or Prospect");
const autoBudget={category:"Food",monthly:1000000,paymentStatus:"auto",paidAmount:0,trackingMonth:"2026-08"};
assert.equal(getBudgetProgress(autoBudget,modelTransactions,referenceDate).paid,900000,"History expense still fills the matching Budget meter");
assert.equal(remainingYearExpenseBreakdown({referenceDate,budgets:[autoBudget],yearly:[],events:[],credit:[],transactions:modelTransactions}).recurring,5000000,"History meter usage must not reduce planned Budget obligations");
const signedEventProjection=buildProjection({years:[2026,2027,2028],referenceDate,accountTotal:0,clients:[],budgets:[],yearly:[],events:[{date:"2028-06-01",amount:50000000},{date:"2028-07-01",amount:-5500000}],credit:[],transactions:[],portfolioForYear:()=>0});
assert.equal(signedEventProjection[2].expenses.events,55500000,"Expense entries use absolute obligations and can never cancel another event");

const migration006 = read("supabase/migrations/006_client_types_yearly_status.sql");
for (const marker of ["client_type","ending_paid","last_paid_year"]) assert.match(migration006,new RegExp(marker));
assert.doesNotMatch(migration006,/drop\s+table|truncate\s+|delete\s+from/i);
const migration007 = read("supabase/migrations/007_projection_budget_sort_language.sql");
for (const marker of ["payment_status","paid_amount","tracking_month","sort_order","language"]) assert.match(migration007,new RegExp(marker));
assert.doesNotMatch(migration007,/drop\s+table|truncate\s+|delete\s+from/i);
const migration008 = read("supabase/migrations/008_event_credit_sort_order.sql");
for (const marker of ["planned_events","credit_items","sort_order","tracking_month"]) assert.match(migration008,new RegExp(marker));
assert.doesNotMatch(migration008,/drop\s+table|truncate\s+|delete\s+from/i);
const migration009 = read("supabase/migrations/009_entrusted_funds.sql");
for (const marker of ["entrusted_funds","deduction_source","is_settled","sort_order","enable row level security"]) assert.match(migration009,new RegExp(marker));
assert.doesNotMatch(migration009,/drop\s+table|truncate\s+|delete\s+from/i);
const migration010 = read("supabase/migrations/010_monthly_budget_sort_order.sql");
for (const marker of ["monthly_budgets","sort_order","monthly_budgets_user_order_idx"]) assert.match(migration010,new RegExp(marker));
assert.doesNotMatch(migration010,/drop\s+table|truncate\s+|delete\s+from/i);
const migration011 = read("supabase/migrations/011_stock_cash_wallet.sql");
for (const marker of ["stock_netcash_idr","stock_wallet_usd","app_settings"]) assert.match(migration011,new RegExp(marker));
assert.doesNotMatch(migration011,/drop\s+table|truncate\s+|delete\s+from/i);
const migration012 = read("supabase/migrations/012_trading_portfolio.sql");
for (const marker of ["trading_positions","trading_ledger","trading_snapshots","external_flow_idr","realized_pl_idr","enable row level security"]) assert.match(migration012,new RegExp(marker));
assert.doesNotMatch(migration012,/drop\s+table|truncate\s+|delete\s+from/i);
const migration013 = read("supabase/migrations/013_investment_dividends.sql");
for (const marker of ["investment_dividends","amount_per_share","eligible_shares","record_date","payment_date","credited_at","enable row level security","force row level security"]) assert.match(migration013,new RegExp(marker));
assert.doesNotMatch(migration013,/drop\s+table|truncate\s+|delete\s+from/i);
const migration014 = read("supabase/migrations/014_dividend_credit_reversal.sql");
for (const marker of ["credited_amount_native","credited_currency","credit_reversed_at","investment_dividends_user_credited_idx"]) assert.match(migration014,new RegExp(marker));
assert.doesNotMatch(migration014,/drop\s+table|truncate\s+|delete\s+from/i);
const migration015 = read("supabase/migrations/015_electricity_topups.sql");
for (const marker of ["electricity_topups","amount_kwh","topup_date","topup_time","enable row level security","force row level security","electricity_topups_select_own","electricity_topups_insert_own","electricity_topups_update_own","electricity_topups_delete_own","supabase_realtime"]) assert.match(migration015,new RegExp(marker,"i"));
assert.doesNotMatch(migration015,/drop\s+table|truncate\s+|delete\s+from/i);
const migration016 = read("supabase/migrations/016_crypto_asset_class.sql");
for (const marker of ["asset_type","crypto","binance","USDT","stock_holdings","trading_positions","trading_ledger"]) assert.match(migration016,new RegExp(marker,"i"));
assert.doesNotMatch(migration016,/drop\s+table|truncate\s+|delete\s+from/i);
const migration017 = read("supabase/migrations/017_crypto_multi_quote.sql");
for (const marker of ["USD','IDR','USDT","stock_holdings_crypto_mapping_check","trading_positions_crypto_mapping_check","trading_ledger_crypto_currency_check"]) assert.match(migration017,new RegExp(marker,"i"));
assert.doesNotMatch(migration017,/display_symbol_market_currency|user_id_display_symbol_market_key/i,"Migration 017 must preserve existing position uniqueness");
assert.doesNotMatch(migration017,/drop\s+table|truncate\s+|delete\s+from/i);
const repositorySource = read("src/data/repository.js");
assert.match(repositorySource,/"electricity_topups"/,"Top-ups must be a separate synchronized table");
assert.match(repositorySource,/state\.electricityTopups/,"Top-ups must round-trip through synchronized state");
assert.match(repositorySource,/asset_type/,"Crypto asset type must round-trip through persisted holdings and trades");

const { advanceDividendLifecycle, creditDividendToWallet, dividendReceivables, mergeDividendEvents, projectedDividendForMonth, reconcileDividendState, reverseDividendCredit } = await import("../src/stocks/dividends.js");
const dividendHolding={id:"h1",ticker:"BMRI",currency:"IDR",quantity:100};
const dividendState={stocks:[dividendHolding],stockExtras:{netcashIdr:0,walletUsd:0},dividends:[{id:"d1",holdingId:"h1",eventKey:"bmri:test",ticker:"BMRI",type:"final",currency:"IDR",amountPerShare:10,eligibleShares:100,recordDate:"2026-08-10",paymentDate:"2026-08-20",status:"confirmed",eligibilityStatus:"pending",creditedAt:null}]};
assert.equal(advanceDividendLifecycle(dividendState,new Date("2026-08-11T00:00:00Z")),true);
assert.equal(dividendState.dividends[0].status,"receivable");assert.equal(dividendReceivables(dividendState.dividends,17000),1000);
assert.equal(advanceDividendLifecycle(dividendState,new Date("2026-08-21T00:00:00Z")),true);
assert.equal(dividendState.stockExtras.netcashIdr,1000);assert.equal(dividendState.dividends[0].status,"paid");
assert.equal(advanceDividendLifecycle(dividendState,new Date("2026-08-22T00:00:00Z")),false,"Paid dividends must never be credited twice");
const historicalEvents=[];
assert.equal(mergeDividendEvents(historicalEvents,[{holdingId:"h1",eventKey:"old",type:"interim",currency:"IDR",amountPerShare:5,recordDate:"2026-01-07",paymentDate:"2026-01-14",status:"confirmed"}],[dividendHolding],()=>"old-id",new Date("2026-08-14T00:00:00Z")),true);
assert.equal(historicalEvents[0].eligibilityStatus,"review","Past dividends require historical share review before wallet credit");
assert.equal(creditDividendToWallet({stocks:[dividendHolding],stockExtras:{netcashIdr:0,walletUsd:0},dividends:historicalEvents},historicalEvents[0],new Date("2026-08-14T00:00:00Z")),true);
assert.equal(projectedDividendForMonth([{currency:"USD",amountPerShare:1,eligibleShares:2,paymentDate:"2027-05-10",status:"confirmed",creditedAt:null}],2027,4,17000),34000);
const duplicateDividendState={stockExtras:{netcashIdr:7539138.78,walletUsd:0},dividends:[
 {id:"official",holdingId:"h1",ticker:"BMRI",eventKey:"official",type:"final",currency:"IDR",amountPerShare:376.956939,eligibleShares:10000,exDate:"2026-05-11",paymentDate:"2026-05-25",status:"paid",eligibilityStatus:"locked",sourceProvider:"Bank Mandiri IR",creditedAt:"2026-05-25T00:00:00Z",creditedAmountNative:3769569.39},
 {id:"yahoo",holdingId:"h1",ticker:"BMRI",eventKey:"yahoo",type:"regular",currency:"IDR",amountPerShare:376.95694,eligibleShares:10000,exDate:"2026-05-11",status:"paid",eligibilityStatus:"locked",sourceProvider:"Yahoo corporate actions",creditedAt:"2026-05-25T00:00:00Z",creditedAmountNative:3769569.4}
]};
assert.equal(reconcileDividendState(duplicateDividendState,{year:2026}),true,"The same issuer dividend from two providers must collapse into one event");
assert.equal(duplicateDividendState.dividends.length,1);assert.ok(Math.abs(duplicateDividendState.stockExtras.netcashIdr-3769569.39)<.02,"A duplicate credited dividend must also be removed from wallet balance");
assert.equal(reverseDividendCredit(duplicateDividendState,duplicateDividendState.dividends[0],new Date("2026-08-14T00:00:00Z")),true);
assert.ok(Math.abs(duplicateDividendState.stockExtras.netcashIdr)<.02,"Cancelling a dividend credit must reverse its exact wallet amount");

const { amountToIdr, applyOpeningPosition, applyTrade, archiveClosedTradingPositions, cashEvent, equityBenchmarkMetrics, performancePreview, performanceSeries, reconcileTradingPositions, removeTradingLedgerEntry, removeTradingPositionData, setTradingWalletBalance, tradingMetrics, tradingTargetSimulation, tradingWallet, upsertDailySnapshot } = await import("../src/trading/model.js");
const tradePosition={id:"p1",ticker:"MU",market:"NASDAQ",currency:"USD",quantity:0,avg:0,current:0};
const tradingLedger=[cashEvent({type:"deposit",currency:"USD",amount:1000,date:"2026-01-02",fxRate:16000,id:"cash1"})];
const editableWallet=[];
assert.equal(setTradingWalletBalance({ledger:editableWallet,currency:"USD",target:250,date:"2026-01-02",fxRate:16000,id:"set1"}).type,"deposit");
assert.equal(tradingWallet(editableWallet).usd,250,"Manual Trading wallet edit must set the exact requested balance");
assert.equal(setTradingWalletBalance({ledger:editableWallet,currency:"USD",target:90,date:"2026-01-03",fxRate:16000,id:"set2"}).type,"withdraw");
assert.equal(tradingWallet(editableWallet).usd,90,"Reducing a manual Trading wallet balance must create an adjustment, not a loss");
assert.equal(setTradingWalletBalance({ledger:editableWallet,currency:"USD",target:90,date:"2026-01-04",fxRate:16000,id:"set3"}),null,"An unchanged wallet balance must not create ledger noise");
tradingLedger.push(applyTrade({position:tradePosition,type:"buy",quantity:1,price:500,date:"2026-01-02",fxRate:16000,id:"buy1"}));
tradePosition.current=600;
let tradeMetrics=tradingMetrics({positions:[tradePosition],ledger:tradingLedger,fxRate:16000});
assert.equal(tradeMetrics.totalPl,1600000,"Trading deposits fund equity but never count as gain");
tradingLedger.push(cashEvent({type:"withdraw",currency:"USD",amount:100,date:"2026-02-02",fxRate:16000,id:"cash2"}));
tradeMetrics=tradingMetrics({positions:[tradePosition],ledger:tradingLedger,fxRate:16000});
assert.equal(tradeMetrics.totalPl,1600000,"Trading withdrawals must not become losses");
tradingLedger.push(applyTrade({position:tradePosition,type:"sell",quantity:1,price:700,date:"2026-02-02",fxRate:16000,id:"sell1"}));
tradeMetrics=tradingMetrics({positions:[tradePosition],ledger:tradingLedger,fxRate:16000});
assert.equal(tradeMetrics.realized,3200000,"Sell execution must realize P/L using the stored cost basis and FX rate");
assert.equal(tradeMetrics.realizedCost,8000000,"Realized return must use only the sold Trading cost basis");
assert.equal(tradeMetrics.realizedReturn,40,"Accumulated Trading gain/loss percentage must be realized-only");
const snapshots=[];upsertDailySnapshot(snapshots,{equity:16000000,externalFlows:16000000,holdingsValue:16000000,cashValue:0},500,"2026-01-02");
upsertDailySnapshot(snapshots,{equity:17600000,externalFlows:16000000,holdingsValue:17600000,cashValue:0},550,"2026-02-02");
const comparison=performanceSeries(snapshots,"ALL",new Date("2026-02-02"));
assert.ok(Math.abs(comparison.portfolioReturn-10)<1e-9);assert.ok(Math.abs(comparison.spyReturn-10)<1e-9);
const sameDayPreview=performancePreview([{id:"base",date:"2026-02-02",equityIdr:15520000,netContributionsIdr:16000000,holdingsValueIdr:15520000,cashValueIdr:0,spyPrice:500}],{equity:15520000,externalFlows:16000000,holdingsValue:15520000,cashValue:0},510,new Date("2026-02-02"));
const sameDayComparison=performanceSeries(sameDayPreview,"ALL",new Date("2026-02-02"));
assert.ok(Math.abs(sameDayComparison.portfolioReturn+3)<1e-9,"Same-day Trading performance must work before any sell");
assert.ok(Math.abs(sameDayComparison.spyReturn-2)<1e-9,"SPY must compare its current API quote with the opening-day baseline");
const target=tradingTargetSimulation({quantity:2,avg:100,currency:"USD"},125,16000);
assert.equal(target.projectedValueIdr,4000000);assert.equal(target.projectedPlIdr,800000);assert.equal(target.projectedReturn,25);
assert.equal(amountToIdr(600,"USDT",17000),10200000,"USDT must use the documented USD/IDR normalization approximation");
const cryptoInvestment={quantity:0.01,avg:60000,current:65000,currency:"USDT",assetType:"crypto"};
assert.equal(cryptoInvestment.quantity*cryptoInvestment.avg,600,"Crypto Investment cost must preserve fractional quantity and USDT price");
assert.equal(cryptoInvestment.quantity*cryptoInvestment.current,650,"Crypto Investment value must preserve fractional quantity and USDT price");
const cryptoPosition={id:"crypto-p1",ticker:"BTC",assetType:"crypto",currency:"USDT",quantity:0.05,avg:60000,current:65000};
const cryptoLedger=[applyOpeningPosition({position:cryptoPosition,date:"2026-08-20",fxRate:17000,id:"crypto-open"})];
cryptoLedger.push(applyTrade({position:cryptoPosition,type:"sell",quantity:0.02,price:65000,date:"2026-08-21",fxRate:17000,id:"crypto-sell"}));
assert.ok(Math.abs(cryptoPosition.quantity-0.03)<1e-12,"Crypto partial sell must preserve fractional remaining quantity");
assert.equal(cryptoLedger[1].assetType,"crypto");
assert.equal(cryptoLedger[1].realizedPlIdr,1700000,"Crypto realized P/L must use the existing cost-basis method");
const cryptoMetrics=tradingMetrics({positions:[cryptoPosition],ledger:cryptoLedger,fxRate:17000});
assert.equal(cryptoMetrics.unrealized,2550000,"Crypto unrealized P/L must use current USDT value and normalized IDR");
const mixedBenchmark=equityBenchmarkMetrics({positions:[{assetType:"equity",currency:"USD",quantity:1,avg:100,current:110},{assetType:"crypto",market:"CRYPTO",currency:"USDT",quantity:1,avg:60000,current:65000}],ledger:[{assetType:"equity",type:"opening",externalFlowIdr:1700000,cashDeltaIdr:0,cashDeltaUsd:0},{assetType:"crypto",type:"opening",externalFlowIdr:102000000,cashDeltaIdr:0,cashDeltaUsd:0}],fxRate:17000});
assert.equal(mixedBenchmark.holdingsValue,1870000,"Mixed benchmark must retain the equity holding component");
assert.equal(mixedBenchmark.externalFlows,1700000,"Mixed benchmark must exclude Crypto external flows");
const { historicalCryptoQuote } = await import("../src/trading/crypto-lifecycle.js");
const closedBtcUsd={id:"btc-tombstone",ticker:"BTC",market:"CRYPTO",assetType:"crypto",currency:"USD",quantity:0,date:"2026-08-20",__createdAt:"2026-08-20T10:00:00Z"};
const closedBtcLedger=[{ticker:"BTC",market:"CRYPTO",assetType:"crypto",currency:"USD",type:"opening",date:"2026-08-20",__createdAt:"2026-08-20T09:00:00Z"},{ticker:"BTC",market:"CRYPTO",assetType:"crypto",currency:"USD",type:"sell",date:"2026-08-21",__createdAt:"2026-08-21T09:00:00Z"}];
assert.equal(historicalCryptoQuote("BTC",{positions:[closedBtcUsd],ledger:closedBtcLedger}),"USD","Closed BTC history must lock Trading re-entry to its original quote");
assert.equal(historicalCryptoQuote("BTC/IDR",{positions:[closedBtcUsd],ledger:closedBtcLedger}),"USD","Pair notation must not override an authoritative historical quote");
const closedBtcUsdt={...closedBtcUsd,id:"btc-usdt",currency:"USDT"};
assert.equal(historicalCryptoQuote("BTC",{positions:[closedBtcUsdt],ledger:[]}),"USDT","Historical USDT BTC must remain USDT on re-entry");
assert.equal(historicalCryptoQuote("ETH",{positions:[],ledger:[]}),null,"Brand-new ETH must have no inherited quote");
const removed=removeTradingPositionData({positions:[{id:"p1"},{id:"p2"}],ledger:[{id:"l1",positionId:"p1",date:"2026-02-01"},{id:"l2",positionId:"p2",date:"2026-01-01"}],snapshots:[{date:"2026-01-01"},{date:"2026-02-01"}]},"p1");
assert.deepEqual(removed.positions,[{id:"p2"}]);assert.deepEqual(removed.ledger,[{id:"l2",positionId:"p2",date:"2026-01-01"}]);assert.deepEqual(removed.snapshots,[{date:"2026-01-01"}]);
const ledgerDeletion=removeTradingLedgerEntry({positions:[],ledger:[{id:"deposit-a",type:"deposit",date:"2026-01-02",cashDeltaUsd:100,externalFlowIdr:1600000},{id:"deposit-b",type:"deposit",date:"2026-02-02",cashDeltaUsd:50,externalFlowIdr:800000}],snapshots:[{date:"2026-01-02"},{date:"2026-02-02"}]},"deposit-b");
assert.deepEqual(ledgerDeletion.ledger.map(row=>row.id),["deposit-a"],"Deleting a Trading ledger record must remove only that execution");
assert.deepEqual(ledgerDeletion.snapshots,[{date:"2026-01-02"}],"Trading performance must be rebuilt from the deleted record date");
assert.ok(applyOpeningPosition({position:{id:"p2",ticker:"MU",currency:"USD",quantity:1,avg:978},date:"2026-01-01",fxRate:16000,id:"open"}).externalFlowIdr>0);
const staleSoldPosition={id:"stale",ticker:"MU",currency:"USD",quantity:1,avg:100,current:80};
const staleSoldLedger=[
  applyOpeningPosition({position:{...staleSoldPosition},date:"2026-01-01",fxRate:16000,id:"stale-open"}),
  {id:"stale-sell",type:"sell",positionId:"stale",ticker:"MU",quantity:1,price:80,currency:"USD",fxRate:16000,cashDeltaIdr:0,cashDeltaUsd:80,externalFlowIdr:0,realizedPlIdr:-320000,date:"2026-02-01"}
];
assert.equal(reconcileTradingPositions([staleSoldPosition],staleSoldLedger),true,"A cloud-reloaded sold position must be repaired from its Trading ledger");
assert.equal(staleSoldPosition.quantity,0,"A fully sold Trading position must not remain in open holdings");
const repairedSoldMetrics=tradingMetrics({positions:[staleSoldPosition],ledger:staleSoldLedger,fxRate:16000});
assert.equal(repairedSoldMetrics.equity,1280000,"Sell proceeds must appear once in Trading equity, not again as a stale holding");
assert.equal(repairedSoldMetrics.unrealized,0,"A fully sold position cannot retain unrealized P/L");
const archivedSold=archiveClosedTradingPositions({positions:[staleSoldPosition],ledger:staleSoldLedger});
assert.equal(archivedSold.positions.length,1,"A closed ticker must retain one reusable sync tombstone");
assert.equal(archivedSold.positions[0].quantity,0,"The closed-position tombstone must never retain open shares");
assert.equal(archivedSold.positions[0].targetPrice,0,"Closing a position must clear its obsolete target price");
assert.equal(archivedSold.positions[0].priceStatus,"closed","A closed ticker must be explicit in synchronized state");
assert.ok(archivedSold.ledger.every(row=>row.positionId===null),"Closed ledger records must survive without retaining the deleted active-position foreign key");
assert.equal(archivedSold.ledger.reduce((sum,row)=>sum+Number(row.realizedPlIdr||0),0),-320000,"Closing an active card must preserve its realized Trading P/L");

const { normalizeStockMapping, quantityForDisplay, quantityForStorage } = await import("../src/stocks/holding.js");
const idxHolding = {ticker:"BMRI",market:"IDX",provider:"finnhub",providerSymbol:"BMRI",currency:"IDR",quantity:10000};
assert.equal(quantityForDisplay(idxHolding), 100);
assert.equal(quantityForStorage("IDX", 100), 10000);
assert.equal(normalizeStockMapping(idxHolding), true);
assert.equal(idxHolding.provider, "yahoo");
assert.equal(quantityForStorage("NASDAQ", 2.8033875), 2.8033875);

process.env.FINNHUB_API_KEY = "test";
process.env.STOCK_SYMBOL_ALLOWLIST = "WDC,BMRI:IDX";
const realFetch = globalThis.fetch;
const { fetchQuote, fetchTradingQuote:fetchProviderTradingQuote, fetchUsdIdrQuote, validateMapping } = await import("../api/_lib/providers.js");
validateMapping({provider:"finnhub",provider_symbol:"WDC",market:"NASDAQ"});
validateMapping({provider:"yahoo",provider_symbol:"BMRI",market:"IDX"});
globalThis.fetch = async () => new Response(JSON.stringify({c:123.45,t:Math.floor(Date.now()/1000)}), {status:200,headers:{"content-type":"application/json"}});
const quote = await fetchQuote({provider:"finnhub",provider_symbol:"WDC",market:"NASDAQ"});
assert.equal(quote.price, 123.45);
assert.equal(quote.provider, "finnhub");
process.env.TWELVE_DATA_API_KEY="twelve-test";
globalThis.fetch = async url => {assert.match(String(url),/api\.twelvedata\.com\/quote\?symbol=MU&prepost=true&apikey=twelve-test/);return new Response(JSON.stringify({symbol:"MU",close:"120",timestamp:Math.floor(Date.now()/1000),is_extended_hours:true}),{status:200,headers:{"content-type":"application/json"}})};
const liveTradingQuote=await fetchProviderTradingQuote("MU");
assert.equal(liveTradingQuote.price,120);assert.equal(liveTradingQuote.provider,"twelve-data");assert.match(liveTradingQuote.coverage,/Twelve Data/);
globalThis.fetch = async url => {
  if(String(url).includes("api.twelvedata.com"))return new Response(JSON.stringify({status:"error",code:429,message:"API credits exhausted"}),{status:200,headers:{"content-type":"application/json"}});
  assert.match(String(url),/finnhub\.io\/api\/v1\/quote\?symbol=MU/);
  return new Response(JSON.stringify({c:121,t:Math.floor(Date.now()/1000)}),{status:200,headers:{"content-type":"application/json"}});
};
const fallbackTradingQuote=await fetchProviderTradingQuote("MU");
assert.equal(fallbackTradingQuote.price,121);assert.equal(fallbackTradingQuote.provider,"finnhub");assert.match(fallbackTradingQuote.coverage,/Finnhub fallback/);
delete process.env.TWELVE_DATA_API_KEY;
globalThis.fetch = async url => {
  assert.match(String(url), /\/BMRI\.JK\?/);
  return new Response(JSON.stringify({chart:{result:[{meta:{regularMarketPrice:4220,regularMarketTime:Math.floor(Date.now()/1000)},timestamp:[Math.floor(Date.now()/1000)],indicators:{quote:[{close:[4220]}]}}],error:null}}), {status:200,headers:{"content-type":"application/json"}});
};
const idxQuote = await fetchQuote({provider:"yahoo",provider_symbol:"BMRI",market:"IDX"});
assert.equal(idxQuote.price, 4220);
assert.equal(idxQuote.provider, "yahoo");
assert.equal(idxQuote.status, "delayed");
globalThis.fetch = async url => {
  assert.match(String(url), /query1\.finance\.yahoo\.com\/v8\/finance\/chart\/IDR%3DX/);
  return new Response(JSON.stringify({chart:{result:[{meta:{regularMarketPrice:17810.25,regularMarketTime:1786134000},timestamp:[1786134000],indicators:{quote:[{close:[17810.25]}]}}],error:null}}), {status:200,headers:{"content-type":"application/json"}});
};
const fxQuote = await fetchUsdIdrQuote();
assert.equal(fxQuote.rate, 17810.25);
assert.equal(fxQuote.provider, "yahoo");
let fxHostCalls=0;
globalThis.fetch = async url => {
  fxHostCalls+=1;
  if(String(url).includes("query1.finance.yahoo.com"))return new Response(JSON.stringify({chart:{result:[{meta:{regularMarketPrice:34468}}],error:null}}), {status:200,headers:{"content-type":"application/json"}});
  assert.match(String(url), /query2\.finance\.yahoo\.com\/v8\/finance\/chart\/IDR%3DX/);
  return new Response(JSON.stringify({chart:{result:[{meta:{regularMarketPrice:17811,regularMarketTime:1786134060},timestamp:[1786134060],indicators:{quote:[{close:[17811]}]}}],error:null}}), {status:200,headers:{"content-type":"application/json"}});
};
const fallbackFxQuote = await fetchUsdIdrQuote();
assert.equal(fxHostCalls,2,"An absurd query1 quote must be rejected before query2 is used");
assert.equal(fallbackFxQuote.rate,17811);
globalThis.fetch = async () => new Response(JSON.stringify({chart:{result:[{meta:{regularMarketPrice:4000}}],error:null}}), {status:200,headers:{"content-type":"application/json"}});
await assert.rejects(fetchUsdIdrQuote(), /Yahoo Finance USD\/IDR unavailable/);
globalThis.fetch = realFetch;

await import("fake-indexeddb/auto");
const { FinanceRepository } = await import("../src/data/repository.js");
const { mutationClear, mutationList } = await import("../src/lib/idb.js");
await mutationClear();
const compatibilityPayloads=[];
const compatibilityRepository=new FinanceRepository({from:()=>({insert:async payload=>{compatibilityPayloads.push(payload);return payload.credited_amount_native!==undefined?{error:{message:"Could not find the 'credited_amount_native' column in the schema cache"}}:{error:null};}})},{id:"compatibility-user"});
await compatibilityRepository.applyOperation({table:"investment_dividends",action:"insert",id:"legacy-dividend",row:{id:"legacy-dividend",user_id:"compatibility-user",credited_amount_native:100,credited_currency:"IDR",credit_reversed_at:null}});
assert.equal(compatibilityPayloads.length,2,"Missing migration 014 must retry once with the legacy dividend schema");
assert.equal(compatibilityPayloads[1].credited_amount_native,undefined,"Compatibility retry must remove only unsupported dividend audit fields");
assert.equal(compatibilityRepository.supportsDividendCreditAudit,false);assert.equal(compatibilityRepository.schemaFallbackUsed,true);
const repository = new FinanceRepository({}, {id:"offline-test-user"});
const id = "22222222-2222-4222-8222-222222222222";
await repository.queueOperation({table:"accounts",action:"insert",id,row:{id,name:"Cash",balance:1},previousUpdatedAt:null});
await repository.queueOperation({table:"accounts",action:"update",id,row:{id,name:"Cash",balance:2},previousUpdatedAt:null});
let queued = await mutationList();
assert.equal(queued.length, 1);
assert.equal(queued[0].action, "insert");
assert.equal(queued[0].row.balance, 2);
await repository.queueOperation({table:"accounts",action:"delete",id,previousUpdatedAt:null});
queued = await mutationList();
assert.equal(queued.length, 0);

const { SyncManager } = await import("../src/sync/sync-manager.js");
let syncSaveCalls=0, retriedTarget=0;
const targetSync = new SyncManager({onState:()=>{},onStatus:()=>{}});
targetSync.repository = {
  pendingCount:async()=>0,
  loadCloud:async()=>({tradingPositions:[{targetPrice:0}]}),
  save:async snapshot=>{
    syncSaveCalls+=1;
    if(syncSaveCalls===1)throw new Error("Synchronization conflict in trading_positions. Cloud data was reloaded.");
    retriedTarget=snapshot.tradingPositions[0].targetPrice;
    return {state:snapshot,pending:0,offline:false};
  }
};
await targetSync.persist({tradingPositions:[{targetPrice:1200}]});
assert.equal(syncSaveCalls,2,"Target sync must retry once after a transient optimistic-lock conflict");
assert.equal(retriedTarget,1200,"Conflict retry must preserve the user's local target price");
assert.equal(targetSync.pendingPersists,0,"The queued-save guard must clear after target persistence");

const appSource = read("app.js");
assert.match(appSource,/function setMobileMenu\(open=false\)/,"Mobile drawer state must have one explicit controller");
assert.match(appSource,/event\.key==="Escape"/,"Escape must dismiss the mobile drawer");
assert.doesNotMatch(appSource, /<input[^>]*type=\"number\"[^>]*data-target=/, "Target-price editors must not use native number steppers");
assert.match(appSource, /class=\"target-price-input\" type=\"text\" inputmode=\"decimal\"/, "Target-price inputs must preserve editable text drafts");
assert.match(appSource, /backdropPress/, "Dialog dismissal must distinguish backdrop clicks from drag-selection gestures");
assert.match(appSource, /fetchUsdIdrRate/, "USD\/IDR live refresh must be wired into the app");
assert.match(appSource,/normalizeQuoteValueToIdr\(v,s\.currency,state\.usdIdr\)/,"USD and USDT holdings must use the centralized quote-to-IDR normalization helper");

assert.match(appSource, /COMPANY_EXPENSE_TAG="Expense Perusahaan"/, "Expense Perusahaan must remain a fixed History-only tag");
assert.match(appSource, /transactions:\[\]/, "Projection calls must explicitly exclude History transactions");
assert.match(appSource, /CHANNEL_PRESETS=\["Offline","Shopee","GrabFood"/, "History editor must expose reusable channel tags");
assert.match(appSource, /DEFAULT_USD_IDR=17810/, "A safe default must repair previously corrupted FX values");
assert.match(appSource, /fixedYearlyIncomeTotal\.textContent=fmt\(fixedIncome\(\)\*12\)/, "Fixed Yearly must equal Fixed Monthly times twelve");
assert.match(appSource, /meta\?\.provider==="yahoo"\?"YAHOO FINANCE"/, "The FX badge must identify Yahoo Finance honestly");
assert.match(appSource, /due due-current/, "Yearly expenses due this month must receive the luminous current-month class");
assert.match(appSource, /data-tx-tag-kind/, "Transaction category and channel chips must act as tag filters");
assert.match(appSource, /currentMonthTransactions/, "History summaries must be scoped to the active month");
assert.match(appSource, /groupExpenses\("category"\).*groupExpenses\("channel"\)/s, "Current expenses must be grouped independently by category and channel");
assert.match(appSource, /tx-current-month/, "The active History month must be visually separate from archives");
assert.match(appSource, /tx-history-archive/, "Previous History months must remain available in Archive");

const electricityIndex = read("index.html");
const electricityCss = read("styles.css");
assert.equal(JSON.parse(read("package.json")).version,"8.3.1","Package version must be v8.3.1");
assert.match(electricityIndex,/<title>CVFinance v8\.3\.1<\/title>/,"Document title must be v8.3.1");
assert.match(read("public/sw.js"),/cvfinance-shell-v8\.3\.1/,"Service-worker cache must invalidate for v8.3.1");
assert.match(electricityIndex,/id="topUpElectricityBtn"[^>]*>\s*TOP UP\s*<\/button>/,"Electricity must expose a distinct TOP UP action");
assert.match(electricityIndex,/id="addElectricityBtn"[^>]*>\s*＋ Reading\s*<\/button>/,"The existing Reading action must remain available");
assert.match(electricityIndex,/id="electricityTopUpModal"/);
assert.match(electricityIndex,/id="electricityTopUpAmount"/);
assert.match(electricityIndex,/id="electricityTopUpCancel"/);
assert.match(electricityIndex,/id="electricityTopUpSubmit"[^>]*>\s*Add Top Up\s*<\/button>/);
assert.doesNotMatch(electricityIndex,/electricityTopUpCost|Top Up Cost/i,"TOP UP must not request an IDR cost");
assert.match(electricityIndex,/Electricity History/,"Combined electricity activity must not be mislabeled as physical readings only");
assert.match(appSource,/latestElectricityBalance\(/,"Latest Meter Balance must use effective physical-reading-plus-top-ups balance");
assert.match(appSource,/state\.electricityTopups/,"Electricity rendering and saving must include persisted top-up events");
assert.match(appSource,/electricityTopUpSubmitting/,"TOP UP must guard against accidental double-submit");
assert.match(electricityCss,/electricity-history-topup/,"TOP UP history rows must have a distinct positive treatment");
assert.match(electricityIndex,/CRYPTO/,"Stocks must expose the Crypto market selector");
assert.match(appSource,/CryptoMarketStream/,"Crypto prices must use one managed combined market stream");
assert.match(appSource,/assetType/,"Stocks and Trading state must distinguish crypto from equity");
assert.doesNotMatch(read(".env.example"),/BINANCE_(API_KEY|SECRET)/,"Binance public market data must not require credentials");
const cryptoApi = read("api/crypto/quote.js");
assert.match(cryptoApi,/data-api\.binance\.vision/,"Crypto REST must be proxied through the official Binance endpoint server-side");
assert.match(cryptoApi,/permissionSets/,"Binance SPOT validation must accept the current exchangeInfo permission shape");
assert.match(cryptoApi,/Crypto symbol not found/);
assert.match(cryptoApi,/Crypto market data is temporarily unavailable/);
const binanceSource = read("src/crypto/binance.js");
assert.match(binanceSource,/CVFINANCE_CRYPTO_API/,"Browser Crypto REST must use the same-origin Vercel API route");
assert.match(electricityIndex,/id="cryptoMarketStatus"/);
assert.equal((appSource.match(/options:\["IDX","NASDAQ","NYSE","CRYPTO"\]/g)||[]).length,2,"Investment and Trading new-entry market selectors must match exactly");
assert.equal((appSource.match(/options:\["USD","IDR","USDT"\]/g)||[]).length,2,"Investment and Trading Crypto quote selectors must match exactly");
assert.match(appSource,/resolveCryptoPair\(parsed\.baseSymbol,parsed\.requestedQuote,state\.usdIdr\)/,"Investment must use the shared multi-quote resolver");
assert.match(appSource,/resolveCryptoPair\(parsed\.baseSymbol,requestedQuote,state\.usdIdr\)/,"Trading must use the shared multi-quote resolver");
assert.match(appSource,/already exists in this portfolio/,"Crypto duplicate detection must be base-symbol scoped");
assert.doesNotMatch(appSource,/row\.currency===resolved\.requestedQuote/,"Crypto duplicate detection must not permit parallel quote-denominated rows");
assert.doesNotMatch(appSource,/options:\[[^\]]*AMEX[^\]]*\]/,"AMEX must not be selectable in new-entry forms");
assert.match(electricityIndex,/id="usdIdrRate"[\s\S]*id="cryptoMarketStatus"/,"Crypto status must sit beside the existing FX status");
const syncInitSource = read("src/sync/sync-manager.js");
assert.match(syncInitSource,/Dashboard initialization failed/,"Post-auth render errors must be reported separately from authentication errors");
assert.match(syncInitSource,/this\.onState\(state\)/,"Authenticated state must still be handed to the app after session success");

const app = read("app.js");
assert.match(app, /portfolioPL\.textContent=`\$\{fmt\(pl\)\} · \$\{percent\(pl,inv\)\}`/);
assert.match(app, /function renderTrading\(\)/);
assert.match(app, /Portfolio vs S&amp;P 500 \/ SPY|tradingPerformanceChart/);
assert.match(app, /Investment Stocks[\s\S]*Trading Stocks/);
assert.match(app, /externalFlows/);
assert.match(app, /openTradingExecution/);
assert.match(app, /Execution Price \/ Share[\s\S]*step:"any"/, "Sell execution price must accept a freely typed manual value");
assert.match(app, /#resetTradingBtn[\s\S]*state\.tradingPositions=\[\];state\.tradingLedger=\[\];state\.tradingSnapshots=\[\]/, "Reset All must clear only the isolated Trading workspace");
assert.match(app, /tradingTotalPl\.textContent=`\$\{metrics\.realized/, "Trading Total Gain\/Loss must use accumulated realized P\/L only");
assert.match(read("index.html"), /STARTING FUNDS/, "Trading capital label must use Starting Funds");
assert.doesNotMatch(read("index.html"), /NET CONTRIBUTIONS/, "The old Net Contributions label must be removed from Trading");
assert.match(app, /switchPage\(state\.page,\{preserveScroll:true\}\)/, "Realtime sync must not force mobile Trading back to the top");
assert.match(app, /if\(!window\.matchMedia\("\(max-width:1024px\)"\)\.matches\)requestAnimationFrame/, "Mobile background sync must never fight touch scrolling with scrollTo");
assert.match(app, /benchmarkSnapshots/, "Trading benchmark must use the equity-only benchmark snapshot component");
assert.match(app, /hasEquityBenchmark/, "Trading benchmark must remain available for equity in mixed Equity + Crypto portfolios");
assert.match(app, /tradingPositions\.addEventListener\("click",handleTradingPositionAction\)/, "Trading actions must use a persistent delegated desktop click handler");
assert.match(app, /archiveClosedTradingPositions\(\{positions:state\.tradingPositions,ledger:state\.tradingLedger\}\)/, "A full sell must archive the active card immediately");
assert.match(app, /already has an active Trading position/, "Ticker duplication must block only another active position");
assert.match(app, /activeTradingPositions=state\.tradingPositions\.filter\(position=>Number\(position\.quantity\)>1e-9\)/, "Trading cards and targets must render active shares only");
assert.match(app, /const reusable=state\.tradingPositions\.find/, "A closed ticker must be reusable for a later position cycle");
assert.match(app, /if\(reusable\)Object\.assign\(reusable,position\)/, "Re-entry must replace the closed tombstone with a new cost basis");
assert.doesNotMatch(app, /\[data-trading-sell\]"\)\.forEach/, "SELL must not rely on a per-render button handler");
assert.match(css, /\.trading-position-card::after\{[^}]*pointer-events:none/, "Trading card decoration must never intercept desktop clicks");
assert.match(css, /\.trading-position-actions\{[^}]*z-index:5/, "Trading action row must stay above card decoration");
assert.match(app, /spyCurrentPrice\.textContent/, "Current SPY API price must be visible");
assert.match(app, /data-trading-target/, "Trading target price must be directly editable");
assert.match(app, /input\.oninput=updateLocal/, "Trading target edits must stay in local state while the editor is active");
assert.match(app, /save\(\{background:silent\}\);if\(!hasActiveEditor\(\)\)renderAll/, "Background quote refresh must not replace an active target editor");
assert.match(app, /tradingTargetSimulation/, "Trading targets must simulate projected value and P\/L");
assert.match(app, /data-trading-delete/, "Every Trading ticker must expose a safe delete action");
assert.doesNotMatch(app, /data-trading-manual|Current \/ Manual Fallback \(USD\)|TAKE PROFIT<input|STOP LOSS<input/, "Trading UI must not expose manual price, take-profit, or stop-loss fields");
assert.match(app, /const decisionMetrics=/);
assert.match(app, /statusText=paid\?"PAID":fmt\(outstanding\)/, "Paid clients must show PAID while unpaid clients show only the nominal value");
assert.doesNotMatch(app, /0 outstanding|outstanding left/, "Client headline copy must not include outstanding wording");
assert.match(app, /function latestTransactionTemplate\(\)/, "Add Transaction must recover the latest saved entry as its next template");
assert.match(app, /txDescription\.value=template\?\.description[\s\S]*txAmount\.value=template\?\.amount/, "Description and Amount must both remain populated from the latest entry");
assert.match(app, /__createdAt:previous\?\.__createdAt\|\|new Date\(\)\.toISOString\(\)/, "New entries must retain insertion order for persistent templates");
assert.match(app, /class="target-years-grid"/, "Target Price groups must use a compact two-up year grid");
assert.match(app, /class="target-year-card"/, "Each future year and target must remain one stable edit card");
assert.match(app, /<details class="year-card prospect-year-card">/, "Future Cash + Assets details must be collapsed until clicked");
assert.match(app, /Financial Action Plan/);

assert.match(app, /2\*60\*1000/, "Trading auto-refresh must use a quota-aware two-minute interval");
assert.match(app, /state\.page==="stocks"&&state\.stockView==="trading"&&!document\.hidden/, "Trading auto-refresh must pause outside Stocks → Trading");
assert.match(app,/refreshInvestmentDividends/,"Investment dividend events must receive a daily provider refresh");
assert.match(app,/advanceDividendLifecycle/,"Dividend receivable and payment states must advance automatically");
assert.match(app,/Opening Cash \+ Investment \+ Trading \+ Income \+ Dividends − Expenses/,"Prospect must disclose confirmed dividend income in its visible equation");

const syncSource = read("src/sync/sync-manager.js");
assert.match(syncSource, /this\.pendingPersists/, "Realtime reloads must wait for queued local saves");
assert.match(syncSource, /await this\.repository\.loadCloud\(\);\s*result = await this\.repository\.save\(snapshot\)/, "Transient optimistic-lock conflicts must retry the unchanged local snapshot");
assert.doesNotMatch(syncSource, /if \(\/conflict\/i\.test\(error\.message \|\| \"\"\)\) \{\s*const cloud[\s\S]*this\.onState\(cloud\)/, "A sync conflict must never overwrite unsaved local target input");

console.log("CVFinance checks passed: schema, RLS markers, PWA, unified Stocks workspace, unchanged Investment/Trading isolation, matching wallet controls, dynamic Investment dividends, historical eligibility review, one-time dividend credit, dividend Prospect income, closed-position sync tombstone, active-only Trading cards and targets, same-ticker re-entry, desktop SELL handler, Trading equity reconciliation, Starting Funds label, mobile document scroll recovery, compact mobile Trading, unrestricted manual Sell price, isolated Reset All, realized-only Trading gain/loss, stable target sync, same-day SPY comparison, visible SPY API quote, safe ticker deletion, Twelve Data primary quotes, Finnhub fallback, Trading Insights, PAID-or-nominal client cards, persistent transaction templates, monthly History archives, Financial Action Plan isolation, Yahoo FX validation, offline queue coalescing, and JavaScript syntax.");
